services:
  db:
    image: postgres:13
    container_name: pesquisasatisfacao_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pesquisasatisfacao_server
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/pscdb

volumes:
  postgres_data:
