services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pesquisasatisfaacao_server
    container_name: pesquisasatisfaacao_server
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/pscdb?schema=public

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: pesquisasatisfaacao_db
    container_name: pesquisasatisfaacao_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pscdb
    volumes:
      - postgres_data:/var/lib/postgresql/data # Para persistir os dados

volumes:
  postgres_data:
